[package]
name = "critic-term"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
critic = { version = "0.1.0", path = "../critic", features = ["rusqlite"] }
crossterm = "0.28.1"
