BEGIN;
CREATE TABLE IF NOT EXISTS titles (
    id INTEGER PRIMARY KEY NOT NULL,
    name STRING NOT NULL,
    UNIQUE(name)
);

CREATE TABLE IF NOT EXISTS criteria_group (
    id INTEGER PRIMARY KEY NOT NULL,
    value STRING NOT NULL,
    UNIQUE(value)
);

CREATE TABLE IF NOT EXISTS criteria (
    id INTEGER PRIMARY KEY NOT NULL,
    value STRING NOT NULL,
    group_id INTEGER NOT NULL,
    FOREIGN KEY (group_id) REFERENCES criteria_group(id) ON DELETE CASCADE,
    UNIQUE(value, group_id)
);

CREATE TABLE IF NOT EXISTS title_criteria (
    id INTEGER PRIMARY KEY NOT NULL,
    elo REAL DEFAULT 1000.0 NOT NULL,
    title_id INTEGER NOT NULL,
    group_id INTEGER NOT NULL,
    FOREIGN KEY (title_id) REFERENCES titles(id) ON DELETE CASCADE
    FOREIGN KEY (group_id) REFERENCES criteria_group(id) ON DELETE CASCADE
    UNIQUE(title_id, group_id)
);

CREATE TABLE IF NOT EXISTS match_history (
    id INTEGER PRIMARY KEY NOT NULL,
    criterion_id INTEGER NOT NULL,
    a_id INTEGER NOT NULL,
    b_id INTEGER NOT NULL,
    score REAL NOT NULL,
    elo_adj_a REAL NOT NULL,
    elo_adj_b REAL NOT NULL,
    time DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (criterion_id) REFERENCES criteria(id) ON DELETE CASCADE,
    FOREIGN KEY (a_id) REFERENCES titles(id) ON DELETE CASCADE,
    FOREIGN KEY (b_id) REFERENCES titles(id) ON DELETE CASCADE
);
COMMIT;
